security:
    role_hierarchy:
        ROLE_PAYMENT_ADMIN_PAYMENTS:
            - ROLE_PAYMENT_ADMIN_PAYMENT_LIST
            - ROLE_PAYMENT_ADMIN_PAYMENT_DETAILS
            - ROLE_PAYMENT_ADMIN_PAYMENT_CREATE
            - ROLE_PAYMENT_ADMIN_PAYMENT_REFUND
        ROLE_PAYMENT_ADMIN_INVOICES:
            - ROLE_PAYMENT_ADMIN_INVOICE_LIST
            - ROLE_PAYMENT_ADMIN_INVOICE_DETAILS
            - ROLE_PAYMENT_ADMIN_INVOICE_CREATE
        ROLE_PAYMENT_ADMIN_CONCEPTS:
            - ROLE_PAYMENT_ADMIN_CONCEPT_LIST
            - ROLE_PAYMENT_ADMIN_CONCEPT_DETAILS
            - ROLE_PAYMENT_ADMIN_CONCEPT_CREATE
        ROLE_PAYMENT_ADMIN_DISCOUNTS:
            - ROLE_PAYMENT_ADMIN_DISCOUNT_LIST
            - ROLE_PAYMENT_ADMIN_DISCOUNT_DETAILS
            - ROLE_PAYMENT_ADMIN_DISCOUNT_CREATE
        ROLE_PAYMENT_ADMIN_FULL:
            - ROLE_PAYMENT_ADMIN_PAYMENTS
            - ROLE_PAYMENT_ADMIN_INVOICES
            - ROLE_PAYMENT_ADMIN_CONCEPTS
            - ROLE_PAYMENT_ADMIN_DISCOUNTS