security:
    role_hierarchy:
        ROLE_PAYMENT_ADMIN_PAYMENTS:
            - ROLE_PAYMENT_ADMIN_PAYMENT_LIST
            - ROLE_PAYMENT_ADMIN_PAYMENT_DETAILS
        ROLE_PAYMENT_ADMIN_INVOICES:
            - ROLE_PAYMENT_ADMIN_INVOICE_LIST
            - ROLE_PAYMENT_ADMIN_INVOICE_DETAILS
        ROLE_PAYMENT_ADMIN_FULL:
            - ROLE_PAYMENT_ADMIN_PAYMENTS
            - ROLE_PAYMENT_ADMIN_INVOICES