sfs_payment_admin_invoices_list:
    controller: sfs_payment.admin.invoice.controller::list
    path: /

sfs_payment_admin_invoices_create:
    controller: sfs_payment.admin.invoice.controller::create
    path: /create

sfs_payment_admin_invoices_read:
    controller: sfs_payment.admin.invoice.controller::read
    path: /{invoice}
