services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\PaymentBundle\Form\Admin\InvoiceCreateFormInterface:
        class: 'Softspring\PaymentBundle\Form\Admin\InvoiceCreateForm'

    Softspring\PaymentBundle\Form\Admin\InvoiceListFilterFormInterface:
        class: 'Softspring\PaymentBundle\Form\Admin\InvoiceListFilterForm'

    Softspring\PaymentBundle\EventListener\Admin\InvoiceListener:
        tags: ['kernel.event_subscriber']

    Softspring\PaymentBundle\Controller\Admin\InvoiceController: ~

    sfs_payment.admin.invoice.controller:
        class: Softspring\CrudlBundle\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\PaymentBundle\Manager\InvoiceManagerInterface'
            $listFilterForm: '@Softspring\PaymentBundle\Form\Admin\InvoiceListFilterFormInterface'
            $createForm: '@Softspring\PaymentBundle\Form\Admin\InvoiceCreateFormInterface'
            $updateForm: null
            $deleteForm: null
            $config:
                entity_attribute: 'invoice'
                list:
                    is_granted: 'ROLE_PAYMENT_ADMIN_INVOICE_LIST'
                    filter_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_LIST_FILTER
                    view_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_LIST_VIEW
                    view: '@@SfsPayment/admin/invoice/list.html.twig'
                    view_page: '@@SfsPayment/admin/invoice/list-page.html.twig'
                    read_route: 'sfs_payment_admin_invoices_read'
                read:
                    is_granted: 'ROLE_PAYMENT_ADMIN_INVOICE_DETAILS'
                    param_converter_key: 'id'
                    view_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_READ_VIEW
                    view: '@@SfsPayment/admin/invoice/read.html.twig'
                create:
                    is_granted: 'ROLE_PAYMENT_ADMIN_INVOICE_CREATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\PaymentBundle\SfsPaymentEvents::ADMIN_INVOICES_CREATE_VIEW
                    view: '@@SfsPayment/admin/invoice/create.html.twig'