services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_payment.entity_manager'

    Softspring\PaymentBundle\Manager\DiscountManagerInterface:
        class: Softspring\PaymentBundle\Manager\DiscountManager
        arguments:
            $targetClass: 'Softspring\PaymentBundle\Model\DiscountInterface'