services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_payment.entity_manager'

    Softspring\PaymentBundle\Manager\InvoiceManagerInterface:
        class: Softspring\PaymentBundle\Manager\InvoiceManager
        arguments:
            $targetClass: 'Softspring\PaymentBundle\Model\InvoiceInterface'
