services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $em: '@sfs_payment.entity_manager'

    Softspring\PaymentBundle\Manager\PaymentManagerInterface:
        class: Softspring\PaymentBundle\Manager\PaymentManager
        arguments:
            $targetClass: 'Softspring\PaymentBundle\Model\PaymentInterface'